### PR TITLE
Configure Aerogear voyager server

### PR DESCRIPTION
**Pull request by supriyanta**

### CODE REVIEW

**Comment by wtrocki** [comment]
I wanted to take look into integration before merge.

**Comment by wtrocki** [comment]
Integration seems ok. At this point we do not need audit and metrics integration etc. Authentication as well.

**Comment by supriyanta** [comment]
What integration you are talking about?
With apollo client?
@wtrocki

**Comment by wtrocki** [comment]
https://github.com/aerogear/aerogear-js-sdk/tree/master/packages/sync
See example integration in: 
https://github.com/aerogear/ionic-showcase

**Comment by supriyanta** [comment]
Could you please give me a link of example react client project?
I'm familiar with react.

**Pull request merged**
